FROM openjdk:8u212-jre
MAINTAINER DamonCai 782099197@qq.com
COPY ./target/dream-auth-1.0-SNAPSHOT.jar /dream-auth-1.0-SNAPSHOT.jar
EXPOSE 7101
ENTRYPOINT ["java","-jar","/dream-auth-1.0-SNAPSHOT.jar"]
